## Acces to RAW Files

In [5]:
import pandas as pd
import os

files_Programme_BACH=os.path.abspath("Programme-BACH.ipynb")
dossier_notebook = os.path.dirname(files_Programme_BACH)
dossier_project = os.path.dirname(dossier_notebook)
dossier_data=os.path.join(dossier_project,"data")
files_merge1=os.path.join(dossier_data,"Code_APE.xlsx")
files_BACH=os.path.join(dossier_data,"export-bach.csv")

#Import the Code_APE files in data, created by the INSEE_code_APE Notebook
Merge1=pd.read_excel(files_merge1,dtype=str)

#import the BACH data export on the Banque de France website (open source)
Data_BACH = pd.read_csv(files_BACH,sep=";")

## Data Cleaning

In [6]:
# Remove the Letter form the section (we are working with Code APE niv2 with only 2 numbers)
Data_BACH["sector"]=Data_BACH["sector"].map(lambda x: x[1:] if len(x)==3 else x)

## Files Merging

In [11]:
Data_merge=pd.merge(Merge1,Data_BACH,how="left",left_on="NIV2",right_on="sector")
Data_merge=Data_merge.set_index("NIV5")

,NIV4,NIV3,NIV2,NIV1,Label NIV5,Label NIV4,Label NIV3,Label NIV2,Label NIV1,country,...,turnover,nb_firms,R11_NBQ,R11_Q1,R11_Q2,R11_Q3,R28_NBQ,R28_Q1,R28_Q2,R28_Q3
NIV5,,,,,,,,,,,,,,,,,,,,,
01.11Z,01.11,01.1,01,A,"Culture de céréales (à l'exception du riz), de...","Culture de céréales (à l'exception du riz), de...",Cultures non permanentes,"Culture et production animale, chasse et servi...","AGRICULTURE, SYLVICULTURE ET PÊCHE",FR,...,15272976.0,4525.0,4325.0,165.88,246.25,436.00,4525.0,-1.71,17.19,38.28
01.12Z,01.12,01.1,01,A,Culture du riz,Culture du riz,Cultures non permanentes,"Culture et production animale, chasse et servi...","AGRICULTURE, SYLVICULTURE ET PÊCHE",FR,...,15272976.0,4525.0,4325.0,165.88,246.25,436.00,4525.0,-1.71,17.19,38.28
01.13Z,01.13,01.1,01,A,"Culture de légumes, de melons, de racines et d...","Culture de légumes, de melons, de racines et d...",Cultures non permanentes,"Culture et production animale, chasse et servi...","AGRICULTURE, SYLVICULTURE ET PÊCHE",FR,...,15272976.0,4525.0,4325.0,165.88,246.25,436.00,4525.0,-1.71,17.19,38.28
01.14Z,01.14,01.1,01,A,Culture de la canne à sucre,Culture de la canne à sucre,Cultures non permanentes,"Culture et production animale, chasse et servi...","AGRICULTURE, SYLVICULTURE ET PÊCHE",FR,...,15272976.0,4525.0,4325.0,165.88,246.25,436.00,4525.0,-1.71,17.19,38.28
01.15Z,01.15,01.1,01,A,Culture du tabac,Culture du tabac,Cultures non permanentes,"Culture et production animale, chasse et servi...","AGRICULTURE, SYLVICULTURE ET PÊCHE",FR,...,15272976.0,4525.0,4325.0,165.88,246.25,436.00,4525.0,-1.71,17.19,38.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96.09Z,96.09,96.0,96,S,Autres services personnels n.c.a.,Autres services personnels n.c.a.,Autres services personnels,Autres services personnels,AUTRES ACTIVITÉS DE SERVICES,FR,...,6883697.0,1406.0,1297.0,161.53,226.58,373.68,1406.0,-21.12,-2.92,10.86
97.00Z,97.00,97.0,97,T,Activités des ménages en tant qu'employeurs de...,Activités des ménages en tant qu'employeurs de...,Activités des ménages en tant qu'employeurs de...,Activités des ménages en tant qu'employeurs de...,ACTIVITÉS DES MÉNAGES EN TANT QU'EMPLOYEURS ; ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98.10Z,98.10,98.1,98,T,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,ACTIVITÉS DES MÉNAGES EN TANT QU'EMPLOYEURS ; ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98.20Z,98.20,98.2,98,T,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,Activités indifférenciées des ménages en tant ...,ACTIVITÉS DES MÉNAGES EN TANT QU'EMPLOYEURS ; ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99.00Z,99.00,99.0,99,U,Activités des organisations et organismes extr...,Activités des organisations et organismes extr...,Activités des organisations et organismes extr...,Activités des organisations et organismes extr...,ACTIVITÉS EXTRA-TERRITORIALES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Function of the R11

In [24]:
def solvabilite(CodeAPE,TB,FP):
    # TB = Total Bilan 
    # S = Ratio de Solvabilité
    #Solvabilité:
    #
    Q1_solvabilite=Data_merge.loc[CodeAPE,"R11_Q1"]
    Q2_solvabilite=Data_merge.loc[CodeAPE,"R11_Q2"]
    Q3_solvabilite=Data_merge.loc[CodeAPE,"R11_Q3"]
    ratio_de_solvabilite_en_fr=(FP/TB)*100
    ratio_de_solvabilite_en_eu=(TB/FP)*100
    ratio_de_solvabilite_en_fr=round(ratio_de_solvabilite_en_fr,3)
    print("Quartile de ratio EU")
    if ratio_de_solvabilite_en_eu<Q1_solvabilite:
        Q_S_phrase=("Q1: Entreprise fait partie du premier quartile du ratio de solvabilité.")
        Q_S="Q1 solvabilité"
    elif (ratio_de_solvabilite_en_eu>=Q1_solvabilite)&(ratio_de_solvabilite_en_eu<Q2_solvabilite):
        Q_S_phrase=("Q2: Entreprise fait partie du deuxieme quartile du ratio de solvabilité.")
        Q_S="Q2 solvabilité"
    elif (ratio_de_solvabilite_en_eu>=Q2_solvabilite)&(ratio_de_solvabilite_en_eu<Q3_solvabilite):
        Q_S_phrase=("Q3: Entreprise fait partie du troisieme quartile du ratio de solvabilité.")
        Q_S="Q3 solvabilité"
    elif ratio_de_solvabilite_en_eu>=Q3_solvabilite:
        Q_S_phrase=("Q4: Entreprise fait partie du quatrieme quartile du ratio de solvabilité.")
        Q_S="Q4 solvabilité"
    else:
        Q_S_phrase=("Manque de données")
        Q_S="Manque de données"
    Q_S_phrase_FR=("L'entreprise a un ratio de solvabilité (avec Ratio FR) de",ratio_de_solvabilite_en_fr,"%")
    #
    #Label:
    #
    LabelNIV2=Data_merge.loc[CodeAPE,"Label NIV2"]
    LabelNIV1=Data_merge.loc[CodeAPE,"Label NIV1"]
    Label=("L'entreprise fait partie de la section",LabelNIV1,"et l'entreprise est dans la sous-partie",LabelNIV2)
    print("Erreur au niveau du choix du return, insérer 'S' ou 'TB', valeur retourné actuelement par défaut: Ratio de Solvabilité")
    return Q_S + "  |||  " +Q_S_phrase+" (avec Ratio EU)"+ "  |||  " +str(Q_S_phrase_FR)+"  |||  "+str(Label)
solvabilite("71.12B",433509,302005)

Quartile de ratio EU
Erreur au niveau du choix du return, insérer 'S' ou 'TB', valeur retourné actuelement par défaut: Ratio de Solvabilité

'Q1 solvabilité  |||  Q1: Entreprise fait partie du premier quartile du ratio de solvabilité. (avec Ratio EU)  |||  ("L\'entreprise a un ratio de solvabilité (avec Ratio FR) de", 69.665, \'%\')  |||  ("L\'entreprise fait partie de la section", \'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES\', "et l\'entreprise est dans la sous-partie", "Activités d\'architecture et d\'ingénierie ; activités de contrôle et analyses techniques")'

## Function of the R28

In [25]:
#R28
def R28(CodeAPE,DU,YQ,YR,YS,CF,CG,EE):
    # DU=empruntd et dettes aupres des etablissements de credit
    # YQ= Engagement de credit bail mobilier
    # YR= engagement de credit bail immobilier
    # YS= efets portés a l escompte et non echus
    # CF= disponibilités, brut
    # CG= disponibilités, amortissement, provisions
    # EE= total bilan
    # R28= "Ratio d’endettement net des établissements de crédit"
    Q1_R28=Data_merge.loc[CodeAPE,"R28_Q1"]
    Q2_R28=Data_merge.loc[CodeAPE,"R28_Q2"]
    Q3_R28=Data_merge.loc[CodeAPE,"R28_Q3"]
    ratio_R28_eu=((DU+0.87*YQ+0.65*YR+YS)-(CF-CG))/EE
    ratio_R28_eu=round(ratio_R28_eu,3)
    if ratio_R28_eu<Q1_R28:
        print("Q1: Entreprise fait partie du premier quartile du ratio d'endettement net des établissements de crédit.")
        Q="Q1 endetement"
    elif (ratio_R28_eu>=Q1_R28)&(ratio_R28_eu<Q2_R28):
        print("Q2: Entreprise fait partie du deuxieme quartile du ratio d'endettement net des établissements de crédit.")
        Q="Q2 endetement"
    elif (ratio_R28_eu>=Q2_R28)&(ratio_R28_eu<Q3_R28):
        print("Q3: Entreprise fait partie du troisieme quartile du ratio d'endettement net des établissements de crédit.")
        Q="Q3 endetement"
    elif ratio_R28_eu>=Q3_R28:
        print("Q4: Entreprise fait partie du quatrieme quartile du ratio d'endettement net des établissements de crédit.")
        Q="Q4 endetement"
    else:
        print("Manque de données")
        Q="Manque de données"
    print("L'entreprise a un ratio d'endettement net des établissements de crédit de",str(ratio_R28_eu)," (ratio EU)")

    #
    #Label:
    #
    LabelNIV2=Data_merge.loc[CodeAPE,"Label NIV2"]
    LabelNIV1=Data_merge.loc[CodeAPE,"Label NIV1"]
    print("L'entreprise fait partie de la section",LabelNIV1,"et l'entreprise est dans la sous-partie",LabelNIV2)
    return Q
R28("71.12B",0,0,0,0,99365,0,464153)

Q3: Entreprise fait partie du troisieme quartile du ratio d'endettement net des établissements de crédit.
L'entreprise a un ratio d'endettement net des établissements de crédit de -0.214  (ratio EU)
L'entreprise fait partie de la section ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES et l'entreprise est dans la sous-partie Activités d'architecture et d'ingénierie ; activités de contrôle et analyses techniques

'Q3 endetement'

## Saving the new file

In [9]:
# Save the table as ".xlsx"
Data_merge.to_excel("BACH_data_merge.xlsx")